using Finbuckle.MultiTenant;
using Finbuckle.MultiTenant.Abstractions;
using Finbuckle.MultiTenant.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Relation_IMS.Models;
using Relation_IMS.Models.Analytics;
using Relation_IMS.Models.CustomerModels;
using Relation_IMS.Models.InventoryModels;
using Relation_IMS.Models.JWTModels;
using Relation_IMS.Models.OrderModels;
using Relation_IMS.Models.PaymentModels;
using Relation_IMS.Models.ProductModels;
using Relation_IMS.Models.UserProfileModels;
using Relation_IMS.Services;

namespace Relation_IMS.Entities;
public class ApplicationDbContext : MultiTenantDbContext
{
    private readonly ICurrentUserService? _currentUserService;

    public ApplicationDbContext(
        IMultiTenantContextAccessor<AppTenantInfo> multiTenantContextAccessor,
        DbContextOptions<ApplicationDbContext> options,
        ICurrentUserService? currentUserService = null)
        : base(multiTenantContextAccessor, options)
    {
        _currentUserService = currentUserService;
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var now = DateTime.UtcNow;
        var userId = _currentUserService?.UserId;

        // Auto-populate audit fields on save for BaseAuditableEntity
        foreach (var entry in ChangeTracker.Entries<BaseAuditableEntity>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedAt = now;
                    entry.Entity.CreatedBy = userId;
                    break;

                case EntityState.Modified:
                    entry.Entity.UpdatedAt = now;
                    entry.Entity.UpdatedBy = userId;
                    break;
            }
        }

        // Capture audit log entries BEFORE save
        var auditEntries = OnBeforeSaveChanges(userId);

        // Execute actual save
        var result = await base.SaveChangesAsync(cancellationToken);

        // Update inserted IDs and save audit logs AFTER save
        await OnAfterSaveChanges(auditEntries, cancellationToken);

        return result;
    }

    public bool IgnoreProductVariantAndItemAudits { get; set; }
    private int _batchAddedProductItemsCount = 0;
    private string? _batchAddedProductVariantIds = null;

    private List<AuditEntry> OnBeforeSaveChanges(int? userId)
    {
        ChangeTracker.DetectChanges();
        var auditEntries = new List<AuditEntry>();

        if (ChangeTracker.Entries<Product>().Any(e => e.State == EntityState.Added))
        {
            IgnoreProductVariantAndItemAudits = true;
        }

        var addedProductItems = ChangeTracker.Entries<ProductItem>().Where(e => e.State == EntityState.Added).ToList();
        if (addedProductItems.Any())
        {
            _batchAddedProductItemsCount = addedProductItems.Count;
            var variantIds = addedProductItems.Select(e => e.Entity.ProductVariantId).Distinct();
            _batchAddedProductVariantIds = string.Join(",", variantIds);
        }

        foreach (var entry in ChangeTracker.Entries<BaseAuditableEntity>())
        {
            if (entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                continue;

            // Always group ProductItem creation into a single audit log
            if (entry.State == EntityState.Added && entry.Entity is ProductItem)
                continue;

            if (IgnoreProductVariantAndItemAudits && entry.State == EntityState.Added && entry.Entity is ProductVariant)
                continue;

            var auditEntry = new AuditEntry(entry)
            {
                TableName = entry.Metadata.GetTableName() ?? entry.Entity.GetType().Name,
                UserId = userId
            };
            auditEntries.Add(auditEntry);

            foreach (var property in entry.Properties)
            {
                if (property.IsTemporary)
                {
                    // value will be generated by the database, get the value after saving
                    auditEntry.AuditType = AuditType.Create;
                    continue;
                }

                string propertyName = property.Metadata.Name;
                if (property.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[propertyName] = property.CurrentValue;
                    continue;
                }

                switch (entry.State)
                {
                    case EntityState.Added:
                        auditEntry.AuditType = AuditType.Create;
                        auditEntry.NewValues[propertyName] = property.CurrentValue;
                        break;
                    case EntityState.Deleted:
                        auditEntry.AuditType = AuditType.Delete;
                        auditEntry.OldValues[propertyName] = property.OriginalValue;
                        break;
                    case EntityState.Modified:
                        if (property.IsModified && property.OriginalValue?.Equals(property.CurrentValue) != true)
                        {
                            auditEntry.ChangedColumns.Add(propertyName);
                            auditEntry.AuditType = AuditType.Update;
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                        }
                        break;
                }
            }
        }

        return auditEntries;
    }

    private async Task OnAfterSaveChanges(List<AuditEntry> auditEntries, CancellationToken cancellationToken)
    {
        bool hasBatchLogs = _batchAddedProductItemsCount > 0;

        if ((auditEntries == null || auditEntries.Count == 0) && !hasBatchLogs)
            return;

        if (auditEntries != null)
        {
            foreach (var auditEntry in auditEntries)
            {
                foreach (var prop in auditEntry.Entry.Properties)
                {
                    if (prop.IsTemporary)
                    {
                        if (prop.Metadata.IsPrimaryKey())
                        {
                            auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                        }
                        else
                        {
                            auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                        }
                    }
                }
                
                // Only add log if not empty
                if (auditEntry.AuditType == AuditType.Update && auditEntry.ChangedColumns.Count == 0) continue;

                AuditLogs.Add(auditEntry.ToAudit());
            }
        }

        if (hasBatchLogs)
        {
            var batchLog = new AuditLog
            {
                UserId = _currentUserService?.UserId,
                Type = AuditType.Create.ToString(),
                TableName = "ProductItems",
                DateTime = DateTime.UtcNow,
                PrimaryKey = "{\"Batch\":\"true\"}",
                NewValues = $"{{\"Message\":\"{_batchAddedProductItemsCount} product items were generated.\", \"Count\":{_batchAddedProductItemsCount}, \"VariantIds\":\"{_batchAddedProductVariantIds}\"}}"
            };
            AuditLogs.Add(batchLog);
            _batchAddedProductItemsCount = 0; // Reset
            _batchAddedProductVariantIds = null;
        }

        await base.SaveChangesAsync(cancellationToken);
    }

    // Configure entity relationships, keys, and seed data
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        // Define composite primary key for UserRole entity (join table for many-to-many)
        // This means the combination of UserId + RoleId uniquely identifies a UserRole record
        modelBuilder.Entity<UserRole>()
            .HasKey(ur => new { ur.UserId, ur.RoleId });
        // Configure relationship: UserRole -> User (many UserRoles belong to one User)
        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.User)
            .WithMany(u => u.UserRoles) // User can have many UserRoles
            .HasForeignKey(ur => ur.UserId); // Foreign key in UserRole points to User.Id
                                             // Configure relationship: UserRole -> Role (many UserRoles belong to one Role)
        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.Role)
            .WithMany(r => r.UserRoles) // Role can have many UserRoles
            .HasForeignKey(ur => ur.RoleId); // Foreign key in UserRole points to Role.Id
                                             // Seed initial Role data in the database
        modelBuilder.Entity<Role>().HasData(
            new Role { Id = 1, Name = "Salesman", Description = "Salesman role" },
            new Role { Id = 2, Name = "Shop Manager", Description = "Shop Manager role" },
            new Role { Id = 3, Name = "Head Manager", Description = "Head Manager role" },
            new Role { Id = 4, Name = "Owner", Description = "Owner role" }
        );
        // Seed initial Client data for authentication (demo purposes)
        modelBuilder.Entity<Client>().HasData(
            new Client
            {
                Id = 1,
                ClientId = "client-app-one", // Unique client identifier used in JWT tokens
                Name = "Demo Client Application One",
                ClientSecret = "fPXxcJw8TW5sA+S4rl4tIPcKk+oXAqoRBo+1s2yjUS4=", // Base64-encoded secret key
                ClientURL = "https://clientappone.example.com", // Used as Audience in JWT validation
                IsActive = true // Active client flag
            },
            new Client
            {
                Id = 2,
                ClientId = "client-app-two",
                Name = "Demo Client Application Two",
                ClientSecret = "UkY2JEdtWqKFY5cEUuWqKZut2o6BI5cf3oexOlCMZvQ=",
                ClientURL = "https://clientapptwo.example.com",
                IsActive = true
            }
        );

        // Seed initial User (Owner)
        modelBuilder.Entity<User>().HasData(
            new User
            {
                Id = 1,
                Firstname = "Mahin Rashid",
                PhoneNumber = "01521583700",
                Email = "mahin@relationims.com",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("relation83700"),
                IsActive = true,
                ShopNo = 0,
                PreferredLanguage = "en",
                PreferredTheme = "light"
            }
        );

        // Seed initial UserRole
        modelBuilder.Entity<UserRole>().HasData(
            new UserRole
            {
                UserId = 1,
                RoleId = 4 // Owner role
            }
        );

        modelBuilder.Entity<Order>()
                .Property(i => i.PaymentStatus)
                .HasConversion<string>();
        modelBuilder.Entity<ProductDefect>()
            .Property(i => i.Status)
            .HasConversion<string>();

        // UserProfile: one-to-one with User
        modelBuilder.Entity<Relation_IMS.Models.UserProfileModels.UserProfile>()
            .HasIndex(up => up.UserId)
            .IsUnique();

        modelBuilder.Entity<Relation_IMS.Models.UserProfileModels.UserProfile>()
            .HasOne(up => up.User)
            .WithOne(u => u.UserProfile)
            .HasForeignKey<Relation_IMS.Models.UserProfileModels.UserProfile>(up => up.UserId);

        // SalaryRecord: many-to-one with User
        modelBuilder.Entity<Relation_IMS.Models.UserProfileModels.SalaryRecord>()
            .HasOne(s => s.User)
            .WithMany(u => u.SalaryRecords)
            .HasForeignKey(s => s.UserId);

        // SalaryRecord: unique constraint - no duplicate month/year for same user
        modelBuilder.Entity<Relation_IMS.Models.UserProfileModels.SalaryRecord>()
            .HasIndex(s => new { s.UserId, s.Month, s.Year })
            .IsUnique();
    }

    //For JWT
    public DbSet<User> Users { get; set; } = null!;
    public DbSet<Role> Roles { get; set; } = null!;
    public DbSet<UserRole> UserRoles { get; set; } = null!;
    public DbSet<Client> Clients { get; set; } = null!;
    public DbSet<RefreshToken> RefreshTokens { get; set; } = null!;
    public DbSet<AuditLog> AuditLogs { get; set; } = null!;

    // For Products
    public DbSet<Product> Products { get; set; }
    public DbSet<ProductVariant> ProductVariants { get; set; }
    public DbSet<ProductColor> ProductColors { get; set; }
    public DbSet<ProductSize> ProductSizes { get; set; }
    public DbSet<Brand> Brands { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<Quarter> Quarters { get; set; }
    public DbSet<Customer> Customers { get; set; }
    public DbSet<Order> Orders { get; set; }
    public DbSet<OrderItem> OrderItems { get; set; }
    public DbSet<ProductItem> ProductItems { get; set; }
    public DbSet<ProductDefect> ProductDefects { get; set; }
    public DbSet<Inventory> Inventories { get; set; }
    public DbSet<InventoryTransferRecord> InventoryTransferRecords { get; set; }
    public DbSet<InventoryTransferRecordItem> InventoryTransferRecordItems { get; set; }
    public DbSet<ProductLot> ProductLots { get; set; }
    public DbSet<OrderPayment> OrderPayments { get; set; }
    public DbSet<CustomerReturnRecord> CustomerReturnRecords { get; set; }
    public DbSet<CustomerReturnItem> CustomerReturnItems { get; set; }
    public DbSet<UserProfile> UserProfiles { get; set; }
    public DbSet<SalaryRecord> SalaryRecords { get; set; }
    public DbSet<ShareCatalog> ShareCatalogs { get; set; }
    public DbSet<TopSellingProduct> TopSellingProducts { get; set; }
    public DbSet<RevenueByCategory> RevenueByCategories { get; set; }
    public DbSet<TopCustomer> TopCustomers { get; set; }
    public DbSet<SalesOverview> SalesOverviews { get; set; }
    public DbSet<InventoryValue> InventoryValues { get; set; }
    public DbSet<StaffPerformanceMonthly> StaffPerformanceMonthlies { get; set; }
    public DbSet<CustomerInsight> CustomerInsights { get; set; }
    public DbSet<CustomerInsightAllTime> CustomerInsightsAllTime { get; set; }
    public DbSet<TodaySale> TodaySales { get; set; }
}